
# This Dockerfile was generated by Skelebot
# Editing this file manually is not advised as all changes will be overwritten by Skelebot

FROM skelebot/python-base:3.6
MAINTAINER Sean Shookman <sms112788@gmail.com>
WORKDIR /app
RUN ["pip", "install", "setuptools"]
COPY . /app
